# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ozzb2b/matcher/v1/matcher.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ozzb2b/matcher/v1/matcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fozzb2b/matcher/v1/matcher.proto\x12\x11ozzb2b.matcher.v1\"\xca\x01\n\x0bRankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x16\n\x0e\x63\x61tegory_slugs\x18\x02 \x03(\t\x12\x15\n\rcountry_codes\x18\x03 \x03(\t\x12\x12\n\ncity_slugs\x18\x04 \x03(\t\x12\x18\n\x10legal_form_codes\x18\x05 \x03(\t\x12\r\n\x05limit\x18\x06 \x01(\x05\x12\x0e\n\x06offset\x18\x07 \x01(\x05\x12\x30\n\ncandidates\x18\x08 \x03(\x0b\x32\x1c.ozzb2b.matcher.v1.Candidate\"\xbe\x01\n\tCandidate\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x16\n\x0e\x63\x61tegory_slugs\x18\x04 \x03(\t\x12\x14\n\x0c\x63ountry_code\x18\x05 \x01(\t\x12\x11\n\tcity_slug\x18\x06 \x01(\t\x12\x17\n\x0flegal_form_code\x18\x07 \x01(\t\x12\x17\n\x0fretrieval_score\x18\x08 \x01(\x02\"K\n\x0eScoredProvider\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x15\n\rmatcher_score\x18\x03 \x01(\x02\"\\\n\x0cRankResponse\x12\x34\n\tproviders\x18\x01 \x03(\x0b\x32!.ozzb2b.matcher.v1.ScoredProvider\x12\x16\n\x0etotal_estimate\x18\x02 \x01(\x05\x32Y\n\x0eMatcherService\x12G\n\x04Rank\x12\x1e.ozzb2b.matcher.v1.RankRequest\x1a\x1f.ozzb2b.matcher.v1.RankResponseBIZGgithub.com/ozzy1986/ozzb2b/apps/matcher/gen/ozzb2b/matcher/v1;matcherv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ozzb2b.matcher.v1.matcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZGgithub.com/ozzy1986/ozzb2b/apps/matcher/gen/ozzb2b/matcher/v1;matcherv1'
  _globals['_RANKREQUEST']._serialized_start=55
  _globals['_RANKREQUEST']._serialized_end=257
  _globals['_CANDIDATE']._serialized_start=260
  _globals['_CANDIDATE']._serialized_end=450
  _globals['_SCOREDPROVIDER']._serialized_start=452
  _globals['_SCOREDPROVIDER']._serialized_end=527
  _globals['_RANKRESPONSE']._serialized_start=529
  _globals['_RANKRESPONSE']._serialized_end=621
  _globals['_MATCHERSERVICE']._serialized_start=623
  _globals['_MATCHERSERVICE']._serialized_end=712
# @@protoc_insertion_point(module_scope)
