# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ozzb2b_api.grpc_gen.ozzb2b.matcher.v1 import matcher_pb2 as ozzb2b_dot_matcher_dot_v1_dot_matcher__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ozzb2b/matcher/v1/matcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatcherServiceStub(object):
    """MatcherService re-ranks a shortlist of provider candidates using a
    lightweight hybrid score (term overlap + facet matching). The caller
    (API) owns retrieval and hydration; the matcher is a stateless scorer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Rank = channel.unary_unary(
                '/ozzb2b.matcher.v1.MatcherService/Rank',
                request_serializer=ozzb2b_dot_matcher_dot_v1_dot_matcher__pb2.RankRequest.SerializeToString,
                response_deserializer=ozzb2b_dot_matcher_dot_v1_dot_matcher__pb2.RankResponse.FromString,
                _registered_method=True)


class MatcherServiceServicer(object):
    """MatcherService re-ranks a shortlist of provider candidates using a
    lightweight hybrid score (term overlap + facet matching). The caller
    (API) owns retrieval and hydration; the matcher is a stateless scorer.
    """

    def Rank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Rank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rank,
                    request_deserializer=ozzb2b_dot_matcher_dot_v1_dot_matcher__pb2.RankRequest.FromString,
                    response_serializer=ozzb2b_dot_matcher_dot_v1_dot_matcher__pb2.RankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ozzb2b.matcher.v1.MatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ozzb2b.matcher.v1.MatcherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatcherService(object):
    """MatcherService re-ranks a shortlist of provider candidates using a
    lightweight hybrid score (term overlap + facet matching). The caller
    (API) owns retrieval and hydration; the matcher is a stateless scorer.
    """

    @staticmethod
    def Rank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ozzb2b.matcher.v1.MatcherService/Rank',
            ozzb2b_dot_matcher_dot_v1_dot_matcher__pb2.RankRequest.SerializeToString,
            ozzb2b_dot_matcher_dot_v1_dot_matcher__pb2.RankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
